create table if not exists public.instagram_posts (
  id bigint generated by default as identity primary key,
  account text not null,
  slot_index integer not null,
  active boolean not null default true,
  slides jsonb not null,
  caption text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (account, slot_index)
);

alter table public.instagram_posts enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'instagram_posts'
      and policyname = 'instagram_posts_service_role_all'
  ) then
    create policy "instagram_posts_service_role_all"
      on public.instagram_posts
      for all
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;
end $$;

insert into public.instagram_posts (account, slot_index, active, slides, caption)
values
  (
    'cliente-x',
    0,
    true,
    '[
      {"eyebrow":"Maturidade","title":"Sua empresa usa IA ou só testa ferramenta?","body":"O primeiro nível é pedir textos. O próximo é redesenhar processos para ganhar velocidade, padrão e escala."},
      {"eyebrow":"Fase 1","title":"IA como copiloto.","body":"Use para escrever melhor, resumir reuniões, analisar documentos e organizar ideias. É o começo, não o destino."},
      {"eyebrow":"Fase 2","title":"IA dentro do processo.","body":"Quando a IA entra no atendimento, vendas, financeiro e suporte, ela deixa de ser curiosidade e vira operação."},
      {"eyebrow":"Fase 3","title":"Agentes executam tarefas inteiras.","body":"O ganho real aparece quando sistemas recebem contexto, tomam passos definidos e entregam trabalho verificável."},
      {"eyebrow":"Decisão","title":"A pergunta mudou.","body":"Não é mais se a empresa vai usar IA. É onde ela vai aplicar primeiro para gerar resultado mensurável."}
    ]'::jsonb,
    'Muita empresa acha que usa IA porque abriu o ChatGPT algumas vezes.

Mas maturidade em IA tem camadas: primeiro você usa como copiloto, depois coloca dentro dos processos e, por fim, cria agentes que executam tarefas com contexto e controle.

O jogo não é testar ferramenta. É transformar rotina em sistema.

#inteligenciaartificial #ia #automacao #gestao #empresas'
  ),
  (
    'cliente-x',
    1,
    true,
    '[
      {"eyebrow":"Vendas","title":"IA não vende sozinha. Ela tira atrito da venda.","body":"O vendedor continua sendo humano. A diferença é que ele chega mais preparado, responde mais rápido e perde menos contexto."},
      {"eyebrow":"Antes","title":"Lead sem histórico vira chute.","body":"Sem registro claro, cada conversa começa do zero. A IA ajuda a recuperar contexto e indicar o próximo melhor passo."},
      {"eyebrow":"Durante","title":"Atendimento precisa de padrão.","body":"Scripts inteligentes, respostas assistidas e resumo automático reduzem falhas sem deixar a conversa robótica."},
      {"eyebrow":"Depois","title":"Follow-up é onde mora dinheiro esquecido.","body":"A IA pode lembrar prazos, priorizar oportunidades e preparar mensagens alinhadas ao estágio do cliente."},
      {"eyebrow":"Resultado","title":"Menos improviso, mais conversão.","body":"Quando vendas vira processo, a IA consegue acelerar o que já funciona e revelar onde o funil está travando."}
    ]'::jsonb,
    'IA em vendas não substitui relacionamento.

Ela organiza contexto, reduz tempo de resposta, melhora follow-up e ajuda o time a enxergar o que precisa acontecer em cada etapa.

A venda continua humana. A operação por trás dela é que fica mais inteligente.

#vendas #inteligenciaartificial #automacao #crm #negocios'
  ),
  (
    'cliente-x',
    2,
    true,
    '[
      {"eyebrow":"Execução","title":"IA resolve execução, não falta de estratégia.","body":"Se o processo é confuso, a IA só acelera a confusão. Antes de automatizar, defina o que bom significa."},
      {"eyebrow":"Clareza","title":"Sem contexto, tudo fica genérico.","body":"Briefing fraco gera resposta fraca. A qualidade da IA depende da qualidade da direção que você entrega."},
      {"eyebrow":"Processo","title":"Transforme rotina em checklist.","body":"O que se repete pode ser descrito. O que pode ser descrito pode ser treinado, automatizado e medido."},
      {"eyebrow":"Controle","title":"Automação boa tem revisão.","body":"IA precisa de critérios, logs e pontos de aprovação. Velocidade sem controle vira risco operacional."},
      {"eyebrow":"Prática","title":"Comece pelo gargalo mais caro.","body":"Escolha uma tarefa repetitiva, demorada e importante. Automatize pequeno, valide rápido e escale com segurança."}
    ]'::jsonb,
    'IA não conserta uma operação sem direção.

Ela executa melhor quando existe contexto, padrão e critério de qualidade. Por isso, antes de sair automatizando tudo, documente o fluxo e escolha um gargalo claro.

Automação boa começa com processo bem pensado.

#ia #processos #automacao #produtividade #gestao'
  ),
  (
    'cliente-x',
    3,
    true,
    '[
      {"eyebrow":"Vibe coding","title":"Criar software ficou mais acessível.","body":"Com IA e ferramentas no-code, ideias internas podem virar protótipos em dias, não meses."},
      {"eyebrow":"Cuidado","title":"Protótipo não é operação.","body":"A velocidade encanta, mas sistemas reais precisam de dados corretos, permissões, testes e manutenção."},
      {"eyebrow":"Uso certo","title":"Comece com ferramentas internas.","body":"Dashboards, calculadoras, triagem de leads e automações simples são ótimos primeiros projetos com IA."},
      {"eyebrow":"Time","title":"Quem entende o processo cria melhor.","body":"A vantagem não é saber programar tudo. É saber explicar bem o problema, as regras e o resultado esperado."},
      {"eyebrow":"Próximo passo","title":"Teste pequeno. Aprenda rápido.","body":"A empresa que aprende a prototipar com IA ganha velocidade para testar ideias antes da concorrência."}
    ]'::jsonb,
    'Vibe coding e no-code com IA estão mudando a forma como empresas criam soluções internas.

Mas o segredo não é sair criando qualquer coisa. É escolher problemas reais, prototipar rápido e validar com quem usa no dia a dia.

Velocidade com critério vira vantagem competitiva.

#vibecoding #nocode #inteligenciaartificial #automacao #inovacao'
  ),
  (
    'cliente-x',
    4,
    true,
    '[
      {"eyebrow":"Liderança","title":"IA não substitui pensamento.","body":"Ela amplia a capacidade de quem sabe perguntar, decidir e revisar. Usar sem critério só escala mediocridade."},
      {"eyebrow":"Erro comum","title":"Delegar decisão para a IA.","body":"A IA pode organizar cenários, levantar riscos e sugerir caminhos. A responsabilidade continua sendo da liderança."},
      {"eyebrow":"Melhor uso","title":"Use IA para pensar melhor.","body":"Peça contrapontos, simulações, resumos e hipóteses. A ferramenta deve melhorar seu raciocínio, não substituir."},
      {"eyebrow":"Cultura","title":"O time precisa de método.","body":"Sem orientação, cada pessoa usa IA de um jeito. Com método, a empresa cria padrão e aprende coletivamente."},
      {"eyebrow":"Futuro","title":"Quem lidera com IA decide mais rápido.","body":"A vantagem está em combinar contexto humano com execução acelerada por sistemas inteligentes."}
    ]'::jsonb,
    'A melhor forma de usar IA não é terceirizar pensamento.

É usar a tecnologia para organizar cenários, questionar hipóteses, acelerar análise e executar com mais qualidade.

IA forte não elimina liderança. Ela exige liderança melhor.

#lideranca #inteligenciaartificial #gestao #produtividade #empresas'
  )
on conflict (account, slot_index) do update
set
  active = excluded.active,
  slides = excluded.slides,
  caption = excluded.caption,
  updated_at = now();
